image: node:latest

before_script:
  - export NODE_ENV=test

variables:
  DB_HOST: mongo
  DB_PORT: 27017


stages:
  - build
  - test

cache:
  paths:
    - node_modules/

services:
  - mongo
  
install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  
test_with_lab:
  stage: test
  script: 
    - npm test
    